language: node_js
node_js:
  - 10
services:
  - docker
env:
  global:
    - PACT_BROKER_BASE_URL=https://freddiecarre.pact.dius.com.au
    - PACT_BROKER_PUBLISH_VERIFICATION_RESULTS=true
    # Encrypted PACT_BROKER_TOKEN
    - secure: A08A3mY3G3IU0NXsLAhw+InlTPzyLN5oCiA9uhVV+udsEY8SG52XJaKRyXiMz2QQgkhP0S2/CMcRPpN4EZX5cF8N34+IfURFMy9/1rb+I5Z00ZetzAUoFQvTlBoH7RW8BDrZbwM1mdYryr1g+0gojZWqvIgGciWTDvu+wao+9E32qUHrzM1s97NKDzqsL2bGcoCyIuxR5NjtAeJd5MWFFP9kikk6ooufcJPUklh1J86/sXJI7luigIt5ImS3XAEjykFNbW7ZT9PXoSD/4ScWXCV/MPD2SyXl4+ke2+ROxzEMKxqS5TjsjOteK4QGO2/yboMEoQlt7OdFCnjPJEhztrID5bf1g8O6O+jzAA5rkxpZDM2Gk09+AogYOFxxyz2rCYz6d3X3H9J2ZmTuVU5XhBvffEWrOHVEEkYO+n1/Wy3NDURjQNLNPfKQp+dYyii2FOYFSSra8R1u05bHE1S+5bwAf0wdPqm8b/jjp17d+kGgqlphmnAq44ZMxNBMwswQUUhLQCugtHLFTxJe/V3s1J41FE77tLQIKjmWrFyWNcAOY3XcEEn4qcIf4U2TpAOcphLccH7HnbGyPznrIyQdhi6qelZLd47o7M51zDcpALNk9e1Z48g/vJiB7HNhoegrcze0YN7WksE6BPW+RSWsSOfQZsHKyD2cEwiBpQGAaFE=
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
  # When a webhook triggers a build, the PACT_URL will be set. In this case, just run the verification step.
  # Otherwise, run the normal build.
  # This is just to get around the fact that Travis CI only has one build definition per repository.
  # Normally you would define a separate job for the webhook triggered verification.
  - >
    if [ -n "${PACT_URL}" ]; then
      make ci_webhook
    else
      make ci
    fi
